# =============================================================================
# Re-judge the saved answers with the validated judge.
#
# improve_judge.py selected Atlas-Chat-9B with the v2 prompt (kappa = 0.797
# against human labels) and re-judged the main run. Two other result sets were
# still scored by the old judge (Qwen2.5-14B, v1 prompt, kappa = 0.538):
#   - second_generator_outputs/generations.json   (point K)
#   - prompt_sensitivity_outputs/generations.json (point G)
# This re-judges both with the validated configuration. No answers are
# regenerated; only the judgments change. The old judgments are kept in
# *_oldjudge columns so the change can be reported.
#
# RUN with a GPU:  python3 rejudge_all.py
# Checkpointed: stopping and rerunning resumes where it left off.
# =============================================================================

CONFIG = {
    "corpus_file": "corpus_v2.json",
    "qa_file": "qa_pairs_wiki.json",
    # Each result set is judged by a model from a DIFFERENT family than the one
    # that generated its answers, to avoid self-preference bias:
    #   prompt_sensitivity answers were generated by Qwen   -> judged by Atlas-Chat
    #   second_generator answers were generated by Atlas-Chat -> judged by Qwen
    # Both use the validated v2 prompt. Report each judge's kappa from
    # judge_improvement/judge_selection.csv.
    "sources": {
        "second_generator": ("second_generator_outputs/generations.json",
                             "Qwen/Qwen2.5-14B-Instruct"),
        "prompt_sensitivity": ("prompt_sensitivity_outputs/generations.json",
                               "MBZUAI-Paris/Atlas-Chat-9B"),
    },
    "batch": 4,
    "max_new_tokens": 32,
    "out": "rejudged",
    "DRY_RUN": False,
}

import os, json, gc
import numpy as np
import pandas as pd
from tqdm import tqdm

OUT = CONFIG["out"]
os.makedirs(OUT, exist_ok=True)

corpus = json.load(open(CONFIG["corpus_file"], encoding="utf-8"))
texts = {c["chunk_id"]: c["text"] for c in corpus}
byid = {q["id"]: q for q in json.load(open(CONFIG["qa_file"], encoding="utf-8"))}

# The validated prompt, identical to PROMPT_V2 in improve_judge.py.
PROMPT_V2 = """النصوص المرجعية:
{context}

السؤال: {question}
الإجابة الصحيحة: {gold}
الإجابة المقدمة: {answer}

قيّم الإجابة المقدمة وفق القواعد التالية:

قاعدة الامتناع: إذا قالت الإجابة المقدمة إن المعلومة غير متوفرة، فالجواب: مدعوم: لا، مطابق: لا.
(إلا إذا كانت الإجابة الصحيحة نفسها تفيد عدم التوفر.)

قاعدة المطابقة:
- يكفي أن تتضمن الإجابة المقدمة الجوهر الصحيح؛ لا يُشترط ذكر كل تفاصيل الإجابة الصحيحة.
- إضافة تفاصيل صحيحة إضافية لا تُبطل المطابقة.
- ذكر الرقم الصحيح ضمن سياق أوسع صحيح يُعدّ مطابقة.
- اختلاف الصياغة أو الترتيب مقبول.
- اختلاف الأرقام أو الأسماء أو التواريخ عن الإجابة الصحيحة يعني: مطابق: لا.

قاعدة الدعم: مدعوم يعني أن كل ما ورد في الإجابة المقدمة موجود صراحة في النصوص المرجعية.

أجب بهذا الشكل فقط وبدون أي شرح:
مدعوم: نعم/لا
مطابق: نعم/لا"""

def parse(v):
    t = (v or "").replace("،", " ")
    f = c = None
    for line in t.split("\n"):
        if "مدعوم" in line and f is None:
            f = int("نعم" in line.split("مطابق")[0])
        if "مطابق" in line:
            c = int("نعم" in line.split("مطابق", 1)[1])
    return (f or 0), (c or 0), int(f is not None and c is not None)

def ctx_text(cids):
    return "\n\n".join(f"[{i+1}] {texts[c]}" for i, c in enumerate(cids))

if CONFIG["DRY_RUN"]:
    _r = np.random.default_rng(0)
    def load_judge(name): print("stub judge:", name)
    def chat_batch(prompts, mnt=32):
        return [f"مدعوم: {'نعم' if _r.random()<.85 else 'لا'}\nمطابق: {'نعم' if _r.random()<.75 else 'لا'}"
                for _ in prompts]
else:
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
    llm = tokenizer = None
    def load_judge(name):
        global llm, tokenizer
        if llm is not None:
            del llm; llm = None; gc.collect(); torch.cuda.empty_cache()
        q4 = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16,
                                bnb_4bit_quant_type="nf4", bnb_4bit_use_double_quant=True)
        tokenizer = AutoTokenizer.from_pretrained(name)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        tokenizer.padding_side = "left"
        llm = AutoModelForCausalLM.from_pretrained(name, quantization_config=q4,
                                                   device_map="auto", torch_dtype=torch.float16).eval()
        print("loaded", name)

    @torch.no_grad()
    def chat_batch(prompts, mnt=32):
        t = [tokenizer.apply_chat_template([{"role": "user", "content": p}], tokenize=False,
                                           add_generation_prompt=True) for p in prompts]
        e = tokenizer(t, return_tensors="pt", padding=True, truncation=True, max_length=4096).to(llm.device)
        o = llm.generate(**e, max_new_tokens=mnt, do_sample=False, pad_token_id=tokenizer.pad_token_id)
        return [tokenizer.decode(g, skip_special_tokens=True).strip() for g in o[:, e["input_ids"].shape[1]:]]

current_judge = None
for name, (path, judge) in CONFIG["sources"].items():
    if not os.path.exists(path):
        print(f"\n[skip] {name}: {path} not found")
        continue
    ckpt = os.path.join(OUT, f"{name}_rejudged.json")
    gens = json.load(open(ckpt if os.path.exists(ckpt) else path, encoding="utf-8"))

    todo = [i for i, g in enumerate(gens) if "judge_version" not in g]
    print(f"\n{name}: {len(gens)} answers, {len(todo)} still to re-judge (judge: {judge})")
    if todo and judge != current_judge:
        load_judge(judge); current_judge = judge
    B = CONFIG["batch"]
    for s in tqdm(range(0, len(todo), B), desc=name):
        idx = todo[s:s + B]
        prompts = [PROMPT_V2.format(context=ctx_text(gens[i]["context"]),
                                    question=byid[gens[i]["qid"]]["msa_query"],
                                    gold=byid[gens[i]["qid"]]["gold_answer"],
                                    answer=gens[i]["answer"]) for i in idx]
        for i, v in zip(idx, chat_batch(prompts, CONFIG["max_new_tokens"])):
            g = gens[i]
            if "correct" in g and "correct_oldjudge" not in g:
                g["correct_oldjudge"], g["faithful_oldjudge"] = g.get("correct"), g.get("faithful")
            g["faithful"], g["correct"], g["judge_parsed"] = parse(v)
            g["judge_raw"], g["judge_version"] = v, f"{judge.split('/')[-1]}/v2"
        json.dump(gens, open(ckpt, "w", encoding="utf-8"), ensure_ascii=False, indent=1)

    df = pd.DataFrame(gens)
    df["refused"] = df.answer.fillna("").str.contains("غير متوفرة").astype(int)
    df.to_csv(os.path.join(OUT, f"{name}_rejudged.csv"), index=False)
    changed = (df.correct != df.correct_oldjudge).mean() if "correct_oldjudge" in df else float("nan")
    print(f"  parse rate {df.judge_parsed.mean():.3f} | verdicts changed vs old judge: {changed:.1%}")

print(f"\nDone. Now run:  python3 final_analysis.py")
